name = "favorites-api"
main = "index.js"
compatibility_date = "2026-04-29"

[vars]
ALLOWED_ORIGINS = "https://garfieldapp.pages.dev"

[[durable_objects.bindings]]
name = "LEADERBOARD"
class_name = "FavoritesLeaderboard"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["FavoritesLeaderboard"]
