name = "corsproxy"
main = "index.js"
compatibility_date = "2026-04-29"

[vars]
ALLOWED_HOSTS = "dirkjan.nl,www.dirkjan.nl,gocomics.com,*.gocomics.com,assets.amuniversal.com,www.arcamax.com,resources.arcamax.com,garfield.fandom.com,static.wikia.nocookie.net"
