name = "corsproxy"
main = "index.js"
compatibility_date = "2026-04-29"

[vars]
ALLOWED_HOSTS = "gocomics.com,*.gocomics.com,assets.amuniversal.com,picayune.uclick.com,www.arcamax.com,resources.arcamax.com,garfield.fandom.com,static.wikia.nocookie.net"

[observability]
enabled = true
head_sampling_rate = 1
